# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 04:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bill_payment', models.IntegerField()),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_city', models.IntegerField()),
                ('city_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_client', models.CharField(max_length=20)),
                ('id_client', models.IntegerField()),
                ('id_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.City')),
            ],
        ),
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dpto', models.IntegerField()),
                ('dpto_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Description_bill_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_payment', models.IntegerField()),
                ('pay_mode', models.CharField(choices=[(b'CM', b'Cash Money'), (b'CC', b'Credit Card')], default=b'CM', max_length=2)),
                ('employee_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.IntegerField()),
                ('name_product', models.CharField(max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=8)),
                ('stock', models.IntegerField()),
                ('img_product', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product_type', models.IntegerField()),
                ('product_type', models.CharField(max_length=30, unique=True)),
                ('product_description', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_provider', models.IntegerField()),
                ('provider_name', models.CharField(max_length=30)),
                ('tel_provider', models.IntegerField(unique=True)),
                ('id_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.City')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sale', models.IntegerField()),
                ('quantity_sold', models.IntegerField()),
                ('sale_value', models.DecimalField(decimal_places=3, max_digits=8)),
                ('id_bill_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.Bill_payment')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='id_product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.Product_type'),
        ),
        migrations.AddField(
            model_name='product',
            name='id_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.Provider'),
        ),
        migrations.AddField(
            model_name='city',
            name='id_dpto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.Departament'),
        ),
        migrations.AddField(
            model_name='bill_payment',
            name='id_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.Client'),
        ),
        migrations.AddField(
            model_name='bill_payment',
            name='id_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.Description_bill_payment'),
        ),
    ]
