# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-07 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill_payment',
            fields=[
                ('id_bill_payment', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id_city', models.IntegerField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name_client', models.CharField(max_length=20)),
                ('id_client', models.IntegerField(primary_key=True, serialize=False)),
                ('id_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.City')),
            ],
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id_combo', models.IntegerField(primary_key=True, serialize=False)),
                ('combo_name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id_dpto', models.IntegerField(primary_key=True, serialize=False)),
                ('dpto_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Description_bill_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_payment', models.IntegerField(default=0)),
                ('pay_mode', models.CharField(choices=[('CC', 'Credit Card'), ('CM', 'Cash Money')], default='CM', max_length=2)),
                ('employee_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.IntegerField(primary_key=True, serialize=False)),
                ('name_product', models.CharField(max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=8)),
                ('stock', models.IntegerField(default=0)),
                ('img_product', models.CharField(max_length=30, unique=True)),
                ('id_combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.Combo')),
            ],
        ),
        migrations.CreateModel(
            name='Product_type',
            fields=[
                ('id_product_type', models.IntegerField(primary_key=True, serialize=False)),
                ('product_type', models.CharField(max_length=30, unique=True)),
                ('product_description', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_promotion', models.IntegerField(default=0)),
                ('percent_promotion', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id_provider', models.IntegerField(primary_key=True, serialize=False)),
                ('provider_name', models.CharField(max_length=30)),
                ('tel_provider', models.IntegerField(unique=True)),
                ('id_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.City')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id_sale', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity_sold', models.IntegerField()),
                ('sale_value', models.DecimalField(decimal_places=3, max_digits=8)),
                ('id_bill_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.Bill_payment')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product_type',
            name='id_promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.Promotion'),
        ),
        migrations.AddField(
            model_name='product',
            name='id_product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.Product_type'),
        ),
        migrations.AddField(
            model_name='product',
            name='id_promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.Promotion'),
        ),
        migrations.AddField(
            model_name='product',
            name='id_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.Provider'),
        ),
        migrations.AddField(
            model_name='city',
            name='id_dpto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.Departament'),
        ),
        migrations.AddField(
            model_name='bill_payment',
            name='id_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.Client'),
        ),
        migrations.AddField(
            model_name='bill_payment',
            name='id_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.Description_bill_payment'),
        ),
    ]
