# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-09 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='quantity_products',
            field=models.IntegerField(default=0),
        ),
    ]
