# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-07 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id_products', models.IntegerField(default=0)),
                ('id_combo', models.IntegerField(primary_key=True, serialize=False)),
                ('combo_name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
        ),
    ]
