# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-11 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='id',
        ),
        migrations.AlterField(
            model_name='description_bill_payment',
            name='pay_mode',
            field=models.CharField(choices=[(b'CM', b'Cash Money'), (b'CC', b'Credit Card')], default=b'CM', max_length=2),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='id_promotion',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
