# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-07 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0002_combo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description_bill_payment',
            name='pay_mode',
            field=models.CharField(choices=[('CC', 'Credit Card'), ('CM', 'Cash Money')], default='CM', max_length=2),
        ),
    ]
