# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-14 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0003_auto_20170514_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='description_bill_payment',
            name='pay_mode',
            field=models.CharField(choices=[('CM', 'Cash Money'), ('CC', 'Credit Card')], default='CM', max_length=2),
        ),
    ]
