# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-07 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0003_auto_20170506_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combo',
            name='id_products',
        ),
        migrations.AlterField(
            model_name='description_bill_payment',
            name='pay_mode',
            field=models.CharField(choices=[('CM', 'Cash Money'), ('CC', 'Credit Card')], default='CM', max_length=2),
        ),
    ]
