# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-02 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0003_auto_20170406_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_product',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='description_bill_payment',
            name='pay_mode',
            field=models.CharField(choices=[('CM', 'Cash Money'), ('CC', 'Credit Card')], default='CM', max_length=2),
        ),
    ]
