# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0004_auto_20170502_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description_bill_payment',
            name='pay_mode',
            field=models.CharField(choices=[('CC', 'Credit Card'), ('CM', 'Cash Money')], default='CM', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
