# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 01:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0005_auto_20170502_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_payment',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departament',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='description_bill_payment',
            name='id',
            field=models.AutoField(auto_created=True, default=datetime.datetime(2017, 5, 5, 1, 21, 21, 414025, tzinfo=utc), primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, default=datetime.datetime(2017, 5, 5, 1, 21, 29, 237963, tzinfo=utc), primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_type',
            name='id',
            field=models.AutoField(auto_created=True, default=datetime.datetime(2017, 5, 5, 1, 21, 36, 149459, tzinfo=utc), primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='id',
            field=models.AutoField(auto_created=True, default=datetime.datetime(2017, 5, 5, 1, 21, 39, 509613, tzinfo=utc), primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='id',
            field=models.AutoField(auto_created=True, default=datetime.datetime(2017, 5, 5, 1, 21, 46, 764622, tzinfo=utc), primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill_payment',
            name='id_bill_payment',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bill_payment',
            name='id_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.Client'),
        ),
        migrations.AlterField(
            model_name='bill_payment',
            name='id_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.Description_bill_payment'),
        ),
        migrations.AlterField(
            model_name='city',
            name='id_city',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='city',
            name='id_dpto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.Departament'),
        ),
        migrations.AlterField(
            model_name='client',
            name='id_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.City'),
        ),
        migrations.AlterField(
            model_name='client',
            name='id_client',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='departament',
            name='id_dpto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='description_bill_payment',
            name='id_payment',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='description_bill_payment',
            name='pay_mode',
            field=models.CharField(choices=[(b'CM', b'Cash Money'), (b'CC', b'Credit Card')], default=b'CM', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='id_product',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='id_product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.Product_type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.Provider'),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='id_product_type',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='provider',
            name='id_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.City'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='id_provider',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='id_bill_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.Bill_payment'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='id_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.Product'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='id_sale',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_value',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
