# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-15 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshop', '0006_auto_20170514_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill_payment',
            name='id_payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coffeeshop.Description_bill_payment'),
        ),
        migrations.AlterField(
            model_name='bill_payment',
            name='payment_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='description_bill_payment',
            name='pay_mode',
            field=models.CharField(choices=[('CM', 'Cash Money'), ('CC', 'Credit Card')], default='CM', max_length=2),
        ),
    ]
